In [4]:
# Categorical Variables can take one of a fixed set of values.
# They often use one-hot encoding in which the eplainitory variable
# is represented using a binary feature representing one of its
# possible values.
# Example: Represent cities with one-hot encoding
from sklearn.feature_extraction import DictVectorizer

onehot_encoder = DictVectorizer()

X = [
    {'city': 'New York'},
    {'city': 'San Francisco'},
    {'city': 'Chapel Hill'}
]
print(onehot_encoder.fit_transform(X).toarray())

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [5]:
# Standardization is needed so that one feature's variance does not cause it to
# dominate over the learning algorithm.
from sklearn import preprocessing
import numpy as np

X = np.array([
    [0., 0., 5., 13., 9., 1.],
    [0., 0., 13., 15., 10., 15.],
    [0., 3., 15., 2., 0., 11.]
])
print(preprocessing.scale(X))

[[ 0.         -0.70710678 -1.38873015  0.52489066  0.59299945 -1.35873244]
 [ 0.         -0.70710678  0.46291005  0.87481777  0.81537425  1.01904933]
 [ 0.          1.41421356  0.9258201  -1.39970842 -1.4083737   0.33968311]]


In [6]:
# StandardScaler works by subtracting the mean of a feature from each instance's value
# and then dividing by the feature's standard deviation

# RobustScaler is an alternative which subtracts the median and divides by
# the interquartile range. Quartiles are calulated by splitting sorted datasets
# into four parts of equal size. Second quartile is the median while the
# Interquartile range is the difference of the third and first quartiles.
# This mitigates the effect of outliers

In [ ]:
# Extracting features from text